In [1]:
import numpy as np

In [3]:
np.arange(10)
#it generates array from 0 to 9 (always exclude upper limit)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
np.arange(1,10)
#can also specify starting number

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
np.arange(1,10,2)
#can also specify steps

array([1, 3, 5, 7, 9])

In [7]:
np.arange(1,10,0.5)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. ,
       7.5, 8. , 8.5, 9. , 9.5])

In [9]:
#now as we can see we are only generating integers but what if we want to generate floats
np.arange(1,10,dtype='float64') #dtype refers to data type

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [10]:
#storing the generated array in array
arr = np.arange(1,10)

In [11]:
arr.ndim
#this gives the dimention of array

1

In [12]:
arr.shape
#it gives us shape of array i.e., 9 for 9 elements

(9,)

In [13]:
arr.size
#gives the size

9

In [14]:
arr.dtype
#gives type of data stored in array

dtype('int64')

In [15]:
arr.itemsize
#gives the size of one item in array (in bytes)

8

In [16]:
#calculating the memeory usage for arrays (in bytes)
arr.itemsize*arr.size

72

In [18]:
#Why is numpy used?
#Apart from many usely function in the numpy library numpy does vectorized calculations (i.e., numpy does all the
#different calculations on matrices or 2d 3d arrays in a vectorized manner) so that you get faster output compared
#to normal list based operations
#Example:
%timeit list1 = range(1,1000)  #timeit function just time the operations
%timeit list2 = np.arange(1,1000)
#so here in case of list 1 we have to execute more loops than while using numpy

126 ns ± 0.786 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)
605 ns ± 5.1 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [23]:
#asarray function convert any python list into a numpy array
print(np.asarray([1,2,3,4,5]))
list2d =[[1,2,3],[4,5,6]]
arr2d = np.asarray(list2d)
print(arr2d)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]


In [25]:
#this will give a 3*4 numpy array of zeroes
listofzeros = np.zeros((3,4),dtype='int32') #passing 3,4 as tuple
print(listofzeros)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [28]:
#Linspace
np.linspace(1,4,num=4)

array([1., 2., 3., 4.])

In [29]:
np.linspace(1,4,num=8)
#this will generate any amount of number in a given range so here num=8 means it will generate 8 numbers within the
#range of (1,4) 

array([1.        , 1.42857143, 1.85714286, 2.28571429, 2.71428571,
       3.14285714, 3.57142857, 4.        ])

In [31]:
np.linspace(1,4,num=8,endpoint=False) #remember False in python starts with capital letter
#if we use endpoint = False 4 is excluded from list

array([1.   , 1.375, 1.75 , 2.125, 2.5  , 2.875, 3.25 , 3.625])

In [32]:
#Random generator
np.random.random((3,4))
#this way we will get a 3*4 matrix with random values between 0 and 1

array([[0.12523163, 0.98076502, 0.61549035, 0.40614452],
       [0.71135075, 0.15173963, 0.05998674, 0.13877801],
       [0.80638169, 0.27083348, 0.66804508, 0.69802804]])

In [34]:
rarr = np.random.random((3,4))
#storing random array in 3*6 matrix
print(rarr)

[[0.995919   0.64934539 0.48093762 0.27534529]
 [0.73401241 0.44567063 0.49891889 0.14168418]
 [0.89596722 0.86080143 0.72309068 0.21747493]]


In [35]:
#to calculate max from each column
np.max(rarr,axis=0)  #note axis=0 is column use axis=1 for row

array([0.995919  , 0.86080143, 0.72309068, 0.27534529])

In [36]:
#to calculate min from each row
np.min(rarr,axis=1) #note axis=1 is row use axis=0 for column

array([0.27534529, 0.14168418, 0.21747493])

In [37]:
#to calculate max from whole matrix don't pass any axis
np.max(rarr)

0.9959190018068892

In [38]:
#similarly to calculate median
np.median(rarr,axis=0)

array([0.89596722, 0.64934539, 0.49891889, 0.21747493])

In [39]:
#Reshaping
#this reshapes the array i.e., changes the dimention of array
new_arr = np.reshape(rarr,(12,)) #(12,) means single dimention array of 12 size (tuple format)
print(new_arr)

#general format np.reshape(array, newshape, order='C') here order is index ordering read more in numpy documentations

[0.995919   0.64934539 0.48093762 0.27534529 0.73401241 0.44567063
 0.49891889 0.14168418 0.89596722 0.86080143 0.72309068 0.21747493]


In [40]:
#Slicing in numpy
#creating array rarr of 4*5 dimentions and storing random numbers in it
rarr = np.random.random((4,5))
#note slicing means generating new matrices from given matrix

In [41]:
rarr[:,:] #basic format of slicing first : is for rows and second : is for columns
#now :,: means all rows and all columns

array([[0.59240594, 0.74283254, 0.75769391, 0.15455023, 0.93904328],
       [0.98676453, 0.31889405, 0.0097815 , 0.90026196, 0.3142765 ],
       [0.53282773, 0.37547214, 0.53315197, 0.66002389, 0.20759679],
       [0.22974081, 0.14280759, 0.36496336, 0.83159365, 0.22128509]])

In [42]:
rarr[1:3,:] #to select only 2nd and 3rd rows and all columns 
#note upper limit is always excluded in python also note the index based numbering

array([[0.98676453, 0.31889405, 0.0097815 , 0.90026196, 0.3142765 ],
       [0.53282773, 0.37547214, 0.53315197, 0.66002389, 0.20759679]])

In [43]:
rarr[:,1:] #this will take all rows and columns from 1 till last (here 1 is index based)

array([[0.74283254, 0.75769391, 0.15455023, 0.93904328],
       [0.31889405, 0.0097815 , 0.90026196, 0.3142765 ],
       [0.37547214, 0.53315197, 0.66002389, 0.20759679],
       [0.14280759, 0.36496336, 0.83159365, 0.22128509]])

In [44]:
rarr[1:3,1:3] #just another example

array([[0.31889405, 0.0097815 ],
       [0.37547214, 0.53315197]])

In [45]:
#special notations in slicing i.e., using -1
rarr[:-1,:]
#this means all columns but excluding last row

array([[0.59240594, 0.74283254, 0.75769391, 0.15455023, 0.93904328],
       [0.98676453, 0.31889405, 0.0097815 , 0.90026196, 0.3142765 ],
       [0.53282773, 0.37547214, 0.53315197, 0.66002389, 0.20759679]])

In [46]:
rarr[-1:,:] 
#selecting all columns and only first row
#these special notations can be used to slice out np arrays whose size are unknown

array([[0.22974081, 0.14280759, 0.36496336, 0.83159365, 0.22128509]])

In [47]:
rarr[-1,:] #this also works the same way as above example

array([0.22974081, 0.14280759, 0.36496336, 0.83159365, 0.22128509])

In [48]:
rarr[:,-1] #selecting only last column

array([0.93904328, 0.3142765 , 0.20759679, 0.22128509])